import type { Express } from "express";
import { connectPageBody } from "./connect-page.js";

export const logo = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" rx="56" fill="#12140f"/><path d="M48 72h160M48 128h160M48 184h160" fill="none" stroke="#d7b15e" stroke-width="16" stroke-linecap="round"/><circle cx="188" cy="72" r="16" fill="#7dcea0"/><circle cx="132" cy="128" r="16" fill="#7dcea0"/><circle cx="76" cy="184" r="16" fill="#7dcea0"/></svg>`;

const page = (title: string, body: string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Cohort</title><link rel="icon" href="/icon.svg"><style>body{margin:0;background:#12140f;color:#f4f1e8;font:17px/1.65 system-ui}main{max-width:840px;margin:40px auto;padding:24px}a{color:#e2c27a}h1{line-height:1.15;font-size:40px}h2{margin-top:32px}h3{margin:18px 0 6px}nav,footer{display:flex;flex-wrap:wrap;gap:18px}section{border:1px solid #3a382c;border-radius:16px;padding:22px;margin:22px 0}input,textarea,select,button{font:inherit;box-sizing:border-box;max-width:100%;padding:10px;border:1px solid #6d684f;border-radius:8px;background:#1c1e16;color:inherit}input,textarea{width:100%}label{display:block;margin:12px 0}button{cursor:pointer;margin:12px 8px 12px 0}code,pre{overflow-wrap:anywhere}pre{overflow:auto;background:#1c1e16;padding:12px;border-radius:8px}#message{white-space:pre-wrap}small{color:#c9c2ae}</style></head><body><main><nav><a href="/app">Cohort workspace</a><a href="/connect">Connect an assistant</a><a href="/support">Support</a></nav><h1>${title}</h1>${body}<footer><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/data">Your data</a></footer></main></body></html>`;

export function installPublicPages(app: Express, baseUrl: string) {
  app.get("/access", (_req, res) => res.type("html").send(page("Cohort access", `<p>Curriculum tools are available to existing Cohort accounts with an active Pro subscription or trial. This connection has no curriculum-tool entitlement at present. It cannot change your plan or start a purchase.</p><p>Verify that you connected the intended account. <a href="/connections">Manage the connection</a> or <a href="/support">contact support</a> if access looks incorrect.</p>`)));
  app.get("/icon.svg", (_req, res) => res.type("svg").send(logo));
  app.get("/connect", (_req, res) => res.type("html").send(page("Connect an assistant", connectPageBody(baseUrl))));
  app.get("/privacy", (_req, res) => res.type("html").send(page("Privacy policy", `<p>Effective October 4, 2026. Cohort is operated under the Hutchins App Studio brand. Contact the operator through our <a href="/support">private support form</a>.</p><h2>Information we process</h2><p>We process account identifiers and email provided at sign-in, subscription status and billing references, and curriculum content intentionally sent through the workspace or connected tools: promises, module outcomes, non-contradiction rules, revisions, and modules. Support requests contain the reply email and message you provide.</p><p>We do not receive every conversation automatically. Tools receive only their submitted arguments. Do not include passwords, payment card details, or unrelated personal information in curriculum content.</p><h2>Why and where</h2><p>We use this information to provide curriculum features, authenticate users, enforce subscriptions, respond to support, prevent abuse, and meet legal obligations. Supabase provides authentication and database hosting; the host you deploy provides the service; Google provides optional sign-in; Stripe processes payments. We do not store complete card numbers. Connected MCP clients, including ChatGPT, Claude, Gemini, Grok, Cursor, and other hosts you authorize, receive the curriculum information their authorized tools request and apply their own privacy terms. Service providers may process information outside your country.</p><h2>Control and retention</h2><p>We do not sell curriculum content or use it to train our own models. Saved programs remain until you delete them or request account deletion. Revision history remains with its program. <a href="/data">Export or delete programs</a>, including after a subscription expires. Program deletion removes live curriculum, revisions, and modules; provider backups may persist according to provider retention and are not an instant erasure guarantee. Billing records may be retained for required accounting or dispute handling.</p><p>Use support to request account deletion, correction, access, or questions about retention. Support records are kept while resolving the request and as needed for security or legal obligations. The service uses sign-in storage to maintain your session. No advertising trackers are included.</p><h2>Security and changes</h2><p>Account authentication and database ownership rules protect private programs. No service can promise absolute security. We publish policy changes here with an updated effective date. If local privacy law gives you additional rights, you may exercise them through support.</p>`)));
  app.get("/terms", (_req, res) => res.type("html").send(page("Terms of service", `<p>Effective October 4, 2026. These terms govern Cohort, offered under the Hutchins App Studio brand. Questions and requests go through <a href="/support">support</a>.</p><h2>Your curriculum</h2><p>You retain your rights in content you submit. You grant the operator permission to host, process, retrieve, and transmit it only as needed to provide the service. Submit only content you have the right to use. Do not use the service unlawfully, attempt unauthorized access, or disrupt other users.</p><h2>Accounts and paid access</h2><p>Use your own account and protect your sign-in. Curriculum tools require Cohort Pro or an active trial. The trial lasts 14 days. Billing interval, trial end, and payment terms are shown by Stripe before purchase. Trials may convert to recurring paid subscriptions as disclosed at checkout. Manage cancellation through the billing portal in your account. Cancellation does not automatically delete your data. Contact support for billing mistakes or refund requests; applicable consumer rights continue to apply.</p><h2>Cohort has limits</h2><p>The assistant chooses when to invoke tools, subject to your permissions. Cohort cannot promise that an assistant will always retrieve curriculum before it answers, or that it will catch every contradiction. Review important saved facts and keep exports. Locked facts stay locked until you revise them.</p><h2>Service operation</h2><p>We may change features or restrict access to address abuse, security issues, nonpayment, or legal obligations. We aim to provide reliable access but cannot guarantee uninterrupted operation or error-free assistant output. These terms do not remove rights or remedies that applicable law does not permit us to exclude. Material updates will be published with an updated date.</p><h2>Leaving</h2><p>You can disconnect applications, export or delete programs, cancel billing, and request account deletion. These are separate controls, described on <a href="/data">Your data</a>.</p>`)));
  app.get("/support", (_req, res) => res.type("html").send(page("Contact Cohort", `<p>Send a private support, billing, privacy, or account-deletion request. Include a reply email. Do not send passwords, tokens, payment card details, or your full curriculum.</p><form id="support"><label>Reply email<input name="email" type="email" required maxlength="254"></label><label>How can we help?<textarea name="message" required minlength="10" maxlength="4000" rows="7"></textarea></label><button>Send request</button></form><p id="message" role="status"></p><script>document.getElementById('support').onsubmit=async function(e){e.preventDefault();var b=this.querySelector('button');b.disabled=true;try{var r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:this.email.value,message:this.message.value})});var d=await r.json();if(!r.ok)throw Error(d.error||'Unable to send');document.getElementById('message').textContent='Request received. Reference: '+d.id;this.reset()}catch(e){document.getElementById('message').textContent=e.message}finally{b.disabled=false}};</script>`)));
}

export { page };
